# Generated by Django 5.1.7 on 2025-08-15 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_booking_pet_petowner_pettype_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='breeds', to='server.pettype')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='server.breed'),
        ),
        migrations.CreateModel(
            name='FeedingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('food_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feedings', to='server.pet')),
            ],
        ),
        migrations.CreateModel(
            name='RoomExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='server.room')),
            ],
        ),
    ]
